--- 
abstract: Facilitates Automated Testing for DBIx::Class
author: 
  - Nathan Gray <kolibrie@cpan.org>
build_requires: 
  Class::Accessor::Grouped: 0
  DBD::SQLite: 1.11
  File::Spec::Functions: 0
  Test::Builder::Module: 0
  Test::More: 0.42
distribution_type: module
generated_by: Module::Install version 0.68
license: perl
meta-spec: 
  url: http://module-build.sourceforge.net/META-spec-v1.3.html
  version: 1.3
name: Test-DBIC
no_index: 
  directory: 
    - inc
    - t
recommends: 
  SQL::Translator: 0.08
requires: 
  Class::Accessor::Grouped: 0.03
  DBIx::Class: 0.07005
  perl: 5.6.1
version: 0.01003
